# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/george/Desktop/optimal-algo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/george/Desktop/optimal-algo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/george/Desktop/optimal-algo && $(CMAKE_COMMAND) -E cmake_progress_start /home/george/Desktop/optimal-algo/CMakeFiles /home/george/Desktop/optimal-algo/project-algo/CMakeFiles/progress.marks
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f CMakeFiles/Makefile2 project-algo/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/george/Desktop/optimal-algo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f CMakeFiles/Makefile2 project-algo/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f CMakeFiles/Makefile2 project-algo/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f CMakeFiles/Makefile2 project-algo/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/george/Desktop/optimal-algo && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
project-algo/CMakeFiles/polygon.dir/rule:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f CMakeFiles/Makefile2 project-algo/CMakeFiles/polygon.dir/rule
.PHONY : project-algo/CMakeFiles/polygon.dir/rule

# Convenience name for target.
polygon: project-algo/CMakeFiles/polygon.dir/rule

.PHONY : polygon

# fast build rule for target.
polygon/fast:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f project-algo/CMakeFiles/polygon.dir/build.make project-algo/CMakeFiles/polygon.dir/build
.PHONY : polygon/fast

# Convenience name for target.
project-algo/CMakeFiles/polygon1.dir/rule:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f CMakeFiles/Makefile2 project-algo/CMakeFiles/polygon1.dir/rule
.PHONY : project-algo/CMakeFiles/polygon1.dir/rule

# Convenience name for target.
polygon1: project-algo/CMakeFiles/polygon1.dir/rule

.PHONY : polygon1

# fast build rule for target.
polygon1/fast:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f project-algo/CMakeFiles/polygon1.dir/build.make project-algo/CMakeFiles/polygon1.dir/build
.PHONY : polygon1/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f project-algo/CMakeFiles/polygon.dir/build.make project-algo/CMakeFiles/polygon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f project-algo/CMakeFiles/polygon.dir/build.make project-algo/CMakeFiles/polygon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f project-algo/CMakeFiles/polygon.dir/build.make project-algo/CMakeFiles/polygon.dir/main.cpp.s
.PHONY : main.cpp.s

test_polyg.o: test_polyg.cpp.o

.PHONY : test_polyg.o

# target to build an object file
test_polyg.cpp.o:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f project-algo/CMakeFiles/polygon1.dir/build.make project-algo/CMakeFiles/polygon1.dir/test_polyg.cpp.o
.PHONY : test_polyg.cpp.o

test_polyg.i: test_polyg.cpp.i

.PHONY : test_polyg.i

# target to preprocess a source file
test_polyg.cpp.i:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f project-algo/CMakeFiles/polygon1.dir/build.make project-algo/CMakeFiles/polygon1.dir/test_polyg.cpp.i
.PHONY : test_polyg.cpp.i

test_polyg.s: test_polyg.cpp.s

.PHONY : test_polyg.s

# target to generate assembly for a file
test_polyg.cpp.s:
	cd /home/george/Desktop/optimal-algo && $(MAKE) -f project-algo/CMakeFiles/polygon1.dir/build.make project-algo/CMakeFiles/polygon1.dir/test_polyg.cpp.s
.PHONY : test_polyg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... polygon"
	@echo "... polygon1"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test_polyg.o"
	@echo "... test_polyg.i"
	@echo "... test_polyg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/george/Desktop/optimal-algo && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

